---
- name: Configure servers
  hosts: all
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - common
    - nginx
    - docker
    - aws_cli
    - java
    - bitbucket_user
    - ssh_hardening
