---
- name: Pull Node Exporter image
  docker_image:
    name: quay.io/prometheus/node-exporter
    tag: latest
    source: pull

- name: Run Node Exporter container
  docker_container:
    name: node-exporter
    image: quay.io/prometheus/node-exporter:latest
    state: started
    restart_policy: always
    ports:
      - "9100:9100"
    volumes:
      - "/:/host:ro,rslave"
    command: ["--path.rootfs=/host"]

