---
- name: Ensure Snap is installed
  apt:
    name: snapd
    state: present
  become: true

- name: Ensure Snapd service is running
  service:
    name: snapd
    state: started
    enabled: true
  become: true

- name: Install AWS CLI using Snap
  snap:
    name: aws-cli
    classic: true
    state: present
  become: true

