---
- name: Copy the hardened SSH configuration
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
  notify: Restart SSH

- name: Check which SSH host keys exist
  stat:
    path: "{{ item }}"
  loop:
    - /etc/ssh/ssh_host_dsa_key
    - /etc/ssh/ssh_host_ecdsa_key
    - /etc/ssh/ssh_host_ed25519_key
    - /etc/ssh/ssh_host_rsa_key
  register: ssh_keys

- name: Ensure correct permissions for existing SSH keys
  file:
    path: "{{ item.stat.path }}"
    owner: root
    group: root
    mode: '0600'
  loop: "{{ ssh_keys.results }}"
  when: item.stat.exists

- name: Check which SSH host public keys exist
  stat:
    path: "{{ item }}"
  loop:
    - /etc/ssh/ssh_host_dsa_key.pub
    - /etc/ssh/ssh_host_ecdsa_key.pub
    - /etc/ssh/ssh_host_ed25519_key.pub
    - /etc/ssh/ssh_host_rsa_key.pub
  register: ssh_public_keys

- name: Ensure correct permissions for existing public SSH keys
  file:
    path: "{{ item.stat.path }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ ssh_public_keys.results }}"
  when: item.stat.exists
